M48
; DRILL file {KiCad 8.0.4+dfsg-1} date 2025-05-29T21:12:26+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-29T21:12:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X99.38Y-98.0
X107.0Y-98.0
T2
X104.46Y-89.0
X107.0Y-89.0
T3
X93.0Y-90.46
X93.0Y-93.0
M30
